---

collections:
  - name: vladgh.system
    version: 1.10.1

roles:
  - name: chasinglogic.podman
    version: 1.3.0
  - name: gerlingguy.swap
    version: 1.2.0
  - name: roguh.fwknop
    version: master
