---

  - name: UFW - Install firewall
    ansible.builtin.package:
      name:
        - ufw
      state: present
    when: firewall == 'ufw'

  - name: UFW - Enable, allow SSH & reload
    community.general.ufw:
      state: enabled
      default: deny
      rule: allow
      to_port: "{{ ssh_port | default(22) }}"
      proto: tcp
      comment: "SSH Server"
    when: firewall == 'ufw'