---
# tasks file for basic_setup

# collections:
#   - vladgh.system


  - name: Run 'Common' role
    ansible.builtin.import_role:
      name: vladgh.system.common
  
  - name: Setup firewall
    ansible.builtin.import_tasks: firewall.yml
    when: firewall is defined and firewall != 'NONE'

  - name: Harden SSH access
    ansible.builtin.lineinfile:
      state: present
      path: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - regexp: "^#PORT" 
        line: "PORT {{ ssh_port | default('22') }}"
      - regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
      - regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
    when: ssh_hardend is defined and ssh_hardend

  - name: Install fwknopd
    ansible.builtin.import_role: 
      name: roguh.fwknop
    # vars:
    #   fw_access_timeout: fw_access_timeout || default('30')
    #   open_ports: tcp/{{ ssh_port | default(22) }} }}
    when: fwknopd_enabled is defined and fwknopd_enabled      
  
  - name: Setup sudo privileges
    ansible.builtin.import_tasks: sudo.yml
  
  - name: Clone git repos
    ansible.builtin.import_tasks: repos.yml
    when: git_repos is defined

  - name: Setup Podman containers
    ansible.builtin.import_tasks: podman.yml
    when: podman_pods is defined

  - name: Setup swap space
    ansible.builtin.include_role:
      name: geerlingguy.swap
    when: "swap_file_size | default(-1) > 0"
