---

  - name: Add PAM ssh-agent auth module
    ansible.builtin.package:
      name:
        - libpam-ssh-agent-auth
      state: present

  - name: Add PAM auth for sudo through ssh-agent
    ansible.builtin.lineinfile:
      state: present
      path: /etc/pam.d/sudo
      insertbefore: 'common-auth'
      regexp: 'pam_ssh_agent_auth.so'
      line:  'auth    sufficient     pam_ssh_agent_auth.so file=%h/.ssh/authorized_keys'
  
  - name: Enable passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
    when: sudo_wo_passwd is defined and sudo_wo_passwd
